[custom]
;This is an example external configuration file
;All possible customization settings are shown below

;Options for custom groups
;custom_proxy_group=Proxy`select`.*`[]AUTO`[]DIRECT`.*
;custom_proxy_group=AUTO`url-test`.*`http://www.gstatic.com/generate_204`300
;custom_proxy_group=google`select`.*
;custom_proxy_group=netflix`select`.*
;custom_proxy_group=动画疯`select`(深台|彰化|新北|台)
;custom_proxy_group=fox+`select`(HGC|HKBN|PCCW|HKT|深台|彰化|新北|台|新加坡|sg|hk|tw)
;custom_proxy_group=美区影视`select`(美|美国)
;custom_proxy_group=Global_media`select`.*
;custom_proxy_group=Domestic`select`[]DIRECT`[]Proxy
;custom_proxy_group=Apple`select`[]DIRECT`[]Proxy
;custom_proxy_group=Final`select`[]Proxy`[]DIRECT
;custom_proxy_group=屏蔽广告`select`[]REJECT`[]DIRECT
;custom_proxy_group=UnblockNeteaseMusic`select`云音乐解锁`[]DIRECT
custom_proxy_group=!!import:snippets/groups.txt
custom_proxy_group=🤖 AI`select`JP|US|SG
custom_proxy_group=💬 FCM`select`.*
custom_proxy_group=🎥 NETFLIX`select`HK
custom_proxy_group=🏢 办公`url-test`(HK|港)`https://slack.com/`300
custom_proxy_group=♻️ 自动选择`url-test`(JP|US|TW|SG|TR)`http://www.gstatic.com/generate_204`300

;Options for custom rulesets
enable_rule_generator=true
overwrite_original_rules=true
; ruleset=DIRECT,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Unbreak.list
; ruleset=🌌 YouTube,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Media/YouTube.list
; ruleset=🎥 NETFLIX,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Media/Netflix.list
; ruleset=HBO,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Media/HBO.list
; ruleset=Fox,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Media/Fox.list
; ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/GlobalMedia.list
; ruleset=🌏 港台媒体,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/HKMTMedia.list
; ruleset=📲 电报信息,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Telegram.list
; ruleset=🔰 节点选择,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Global.list
; ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/Apple.list
; ruleset=DIRECT,https://raw.githubusercontent.com/ConnersHua/Profiles/master/Surge/Ruleset/China.list
ruleset=💬 FCM,https://raw.githubusercontent.com/laxy-me/converterRules/refs/heads/master/GoogleFCM.list
ruleset=🎯 全球直连,rules/LocalAreaNetwork.list
ruleset=Ⓜ️ 微软服务,rules/MSServices.list
ruleset=🎯 全球直连,rules/DivineEngine/Surge/Ruleset/Unbreak.list
ruleset=🛑 全球拦截,rules/NobyDa/Surge/AdRule.list
ruleset=🛑 全球拦截,rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list
ruleset=🤖 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🏢 办公,https://raw.githubusercontent.com/laxy-me/converterRules/refs/heads/master/work.list
ruleset=🎥 NETFLIX,rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list
ruleset=🎥 NETFLIX,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🌍 国外媒体,rules/DivineEngine/Surge/Ruleset/StreamingMedia/Streaming.list
ruleset=🌏 国内媒体,https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/ChinaMedia.list
ruleset=🌏 国内媒体,rules/lhie1/Surge/Surge 3/Provider/Media/Bilibili.list
ruleset=🌏 国内媒体,rules/lhie1/Surge/Surge 3/Provider/Media/iQiyi.list
ruleset=🌏 国内媒体,rules/lhie1/Surge/Surge 3/Provider/Media/Letv.list
ruleset=🌏 国内媒体,rules/lhie1/Surge/Surge 3/Provider/Media/MOO.list
ruleset=🌏 国内媒体,rules/lhie1/Surge/Surge 3/Provider/Media/Tencent Video.list
ruleset=🌏 国内媒体,rules/lhie1/Surge/Surge 3/Provider/Media/Youku.list
ruleset=📲 电报信息,rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Github.list
ruleset=🔰 节点选择,rules/DivineEngine/Surge/Ruleset/Global.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/laxy-me/converterRules/refs/heads/master/other.list
ruleset=🍎 苹果服务,rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list
ruleset=🎯 全球直连,rules/DivineEngine/Surge/Ruleset/China.list
ruleset=🎯 全球直连,rules/NobyDa/Surge/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


;Options for custom base configuration file
clash_rule_base=base/all_base.tpl
;surge_rule_base=base/surge.conf
;surfboard_rule_base=base/surfboard.conf
;mellow_rule_base=base/mellow.conf
;quan_rule_base=base/quan.conf
;quanx_rule_base=base/quanx.conf
;loon_rule_base=base/loon.conf
;sssub_rule_base=base/shadowsocks_base.json
;singbox_rule_base=base/singbox.json

;Options for renaming nodes
;rename=Test-(.*?)-(.*?)-(.*?)\((.*?)\)@\1\4x测试线路_自\2到\3
;rename=\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?@$1x

;Options for adding emojis
;add_emoji=true
;remove_old_emoji=true
;emoji=(流量|时间|应急),🏳️‍🌈
;emoji=阿根廷,🇦🇷

;Options for filtering nodes
;include_remarks=
;exclude_remarks=

;[template]
;;variables in the local scope
;clash.dns.port=5353